notifications:
  email:
    on_success: never
    on_failure: change

env: DUGITE_CACHE_DIR=$HOME/.dugite/

os:
  - linux
  - osx

branches:
  only:
    - master
    - v2
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - '8'
  - '10'
  - '11'

cache:
  timeout: 600
  directories:
    - '$HOME/.dugite/'
    - '$HOME/.npm'

install:
  - yarn install
  - yarn build
  - yarn is-it-pretty

script:
  - TEST=1 yarn test
